# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: labiraus/labiraus.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/1a141df6-b338-43ed-b9dc-59595b866d10
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://labiraus.com

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "pages/index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  - name: "reports"
    label: "Reports"
    folder: "_reports"
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: File, name: file, widget: file }
